version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: workwork_postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-workwork}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../env/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - workwork-net

  redis:
    image: redis:7-alpine
    container_name: workwork_redis
    restart: always
    ports:
      - "${REDIS_PORT:-6379}:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data
    networks:
      - workwork-net


volumes:
  postgres_data:
  redis_data:

networks:
  workwork-net: